//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveRichTextToDB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class db_htmlEntities1 : DbContext
    {
        public db_htmlEntities1()
            : base("name=db_htmlEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_html_info> tbl_html_info { get; set; }
    
        public virtual ObjectResult<display_all_HTML_Content_Result> display_all_HTML_Content()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<display_all_HTML_Content_Result>("display_all_HTML_Content");
        }
    
        public virtual int Insert_HTML_Content(string html_content)
        {
            var html_contentParameter = html_content != null ?
                new ObjectParameter("html_content", html_content) :
                new ObjectParameter("html_content", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_HTML_Content", html_contentParameter);
        }
    }
}
